### PR TITLE
Mob Edits 150to160

### PR DESCRIPTION
**Pull request by RyanTaplin1705**
- Behemoth and DarkDevourer libs are confusing / broken. These two are incomplete - will look around to see if I can get some advice on these images.

- Time between teleports on mutated man worm may need adjusting.

### CODE REVIEW

**Comment by Suprcode** [comment]
yes some libs i've noticed are missing images - if possible these need retaking from the official wil files again.

**Comment by Suprcode** [comment]
additions look fine, will merge this tomorrow.

thanks for the help with these

**Comment by RyanTaplin1705** [comment]
no problem, i'll try get behemoth / devourer frames then start on 160 to 170 when I next get free time

**Comment by RyanTaplin1705** [comment]
Also here are the AI's used and tested:
Was unsure whether to have CyanoGhast/ GhastlyLeecher to AI 25 (not sure if they self revive) however couldn't seem to get the CynaoGhast glow effect to reverse.

Name	Ai No.
Gingerbreadman = 0
HalloweenScythe = 0
GhastlyLeecher = 0
CyanoGhast = 0
MutatedManworm = 65
CrazyManworm = 66
MudPile = 3
TailedLion = 0	
PoisonHugger = 8

**Pull request merged**
