### PR TITLE
Heroic Grade Added

### PR DESCRIPTION
**Pull request by JevLOMCN**
Tested and is fully working server and client-side. Creature code added too.

### CODE REVIEW

**Comment by KingdomMir2** [comment]
if (item.Info.Grade == ItemGrade.Mythical)
					NameColour = Color.Plum;
			}
                if (item.Info.Grade == ItemGrade.Heroic)
                    NameColour = Color.Red;
            }
            
            move the Herioic up under Mythical

**Comment by Suprcode** [comment]
looks to still have 1 missing colour check missing in ItemObject

public ItemObject(MapObject dropper, UserItem item, Point manualpoint)

**Comment by JevLOMCN** [comment]
Will add now

**Comment by Suprcode** [comment]
I'm not sure why you've added the entire map editor project in here?

Doesn't want to be part of this solution.

Any map editor changes need to be pull requests in the below repo

https://github.com/suprcode/mir2-mapeditor

**Comment by JevLOMCN** [comment]
All sorted now, New pull request done

**Pull request closed without merging**
