### PR TITLE
NoGroup - Map attribute.

### PR DESCRIPTION
**Pull request by daneo1989**
NoGroup map attribute

### CODE REVIEW

**Comment by Pete107** [comment]
May I suggest toggling the AllowGroup to false rather than back to true.

**Comment by Suprcode** [comment]
Why do we need to change the players own AllowGroup setting at all? There should be logic which just prevents them from adding group members (which it looks like you've done). Then just leave any existing group they're in.

Also prevent them from joining a group when they're on the map.

**Comment by daneo1989** [comment]
I looked into the AllowGroup as suggested. (mostly around SwitchGroup in PlayerObject), 

might be worth also making it so the ClientSide disables the AllowGroup button but the fundamental object in disabling the Invites, Adding, Removing on changing maps is there.

**Comment by Pete107** [comment]
> I looked into the AllowGroup as suggested. (mostly around SwitchGroup in PlayerObject),
> 
> might be worth also making it so the ClientSide disables the AllowGroup button but the fundamental object in disabling the Invites, Adding, Removing on changing maps is there.

Yeah, that's what I meant, just disabling the toggle for the player in general on maps with the attribute by setting the AllowGroup to false, it's just a visual effect is all.

**Comment by Suprcode** [comment]
> I looked into the AllowGroup as suggested. (mostly around SwitchGroup in PlayerObject),
> 
> might be worth also making it so the ClientSide disables the AllowGroup button but the fundamental object in disabling the Invites, Adding, Removing on changing maps is there.

You're changing the players setting though. Theres no need. Just prevent the logic from happening in adding members / joining groups.

**Comment by Suprcode** [comment]
Due to another merge this can no longer be commited. Please correct the change suggested and resubmit the pull request.

**Pull request closed without merging**
