### PR TITLE
Converted to SharpDX

### PR DESCRIPTION
**Pull request by Essensoft-Roc**
1. Get rid of SlimDX dependency vc runtime(Microsoft Visual C++ 2010 Redistributable x64).
2. Preparing for migration to .NET 5.

### CODE REVIEW

**Comment by Suprcode** [comment]
I don't see any benefits gained from converting the project to SharpDX (of which has only recently been upgraded to use SlimDX).

**Comment by Essensoft-Roc** [comment]
I think SharpDX may be better. 
If upgraded to .NET Core or .NET 5.

**Comment by Suprcode** [comment]
Better in what way?

SlimDX should be fully supported on .NET 5 - And you can't convert the client to use Core because of other dependencies on Win Forms.

You're not having any performance gain, and both support 64 bit.

Looking up reading material SharpDx requires more manual memory handling, so likely will pose issues if not managed correctly (unlike SlimDx which handles it for you).

I'm very relucant to merge such a major change unless there are noticable improvements gained from moving.

**Comment by jxsr099** [comment]
image
Please solve it

**Comment by roc916** [comment]
> image
> Please solve it

is closed

**Pull request closed without merging**
