### PR TITLE
Better performance of special effects

### PR DESCRIPTION
**Pull request by OuYangPlane**
Fixed the timing of the sole effect,
fixed the offset of the rebirth 2 effect（file needs to be replaced https://drive.google.com/file/d/104K0wroDyiwAgUjsxGq-AZQn7zieyAee/view?usp=share_link）

### CODE REVIEW

**Comment by Suprcode** [comment]
The libs should be directly from official, so why are the offsets incorrect in the first place?

**Comment by OuYangPlane** [comment]
> The libs should be directly from official, so why are the offsets incorrect in the first place?

This is a problem that cannot be ignored, he does have such an offset

**Comment by OuYangPlane** [comment]
> The libs should be directly from official, so why are the offsets incorrect in the first place?

If you have doubts about the offset of Rebirth 2, you can pass this code first, because the code only changes the playback effect of the animation (he is better), not the coordinate offset

**Comment by Suprcode** [comment]
I've just checked the official Effect.WIL file, and none of those effects exist there.

Where are these effects located in the official client?

**Comment by OuYangPlane** [comment]
> I've just checked the official Effect.WIL file, and none of those effects exist there.
> 
> Where are these effects located in the official client?

D:\Wemade\Mir2Global\Data\Magic3.wil

**Comment by Suprcode** [comment]
Please leave this open. The code will be redone correctly to look at the Magic3

**Pull request closed without merging**
