### PR TITLE
Moon Mist Skill

### PR DESCRIPTION
**Pull request by MousaEqilan**
Skill work like:
Ability to hide your self from Monster and players
Invulnerable for 5 seconds but can`t move.
nRegenerate HP every seconds.

### CODE REVIEW

**Comment by PMySQLQ** [comment]
Moon Mist Skill  error release skill character is invisible and can move

**Comment by PMySQLQ** [comment]
https://www.bilibili.com/video/BV1ip411o7rp/?spm_id_from=333.337.search-card.all.click

Complete collection of professional skills of Hanbok Legend 2

**Comment by PMySQLQ** [comment]
Video reference

Legend of Mir 2 (미 르 2) Complete set of Warrior skills

https://www.bilibili.com/video/BV1ip411o71d/?spm_id_from=333.788

Legend of Mir 2 (미 르 2) Complete set of Wizard skills

Legend of Mir 2 (미 르 2) Complete set of Taoist skills

https://www.bilibili.com/video/BV1XW41137EH/?spm_id_from=333.788

Legend of Mir 2 (미 르 2) Complete set of Assassin skills

https://www.bilibili.com/video/BV1ip411o7rp/?spm_id_from=333.788

Legend of Mir 2 (미 르 2) Complete set of Archer skills

https://www.bilibili.com/video/BV1Up411o73J/?spm_id_from=333.788

**Comment by MousaEqilan** [comment]
> Moon Mist Skill error release skill character is invisible and can move

Are you sure you added all the changes?

**Comment by MousaEqilan** [comment]
> > Moon Mist Skill error release skill character is invisible and can move
> 
> Are you sure you added all the changes?

also this assassin skill

**Comment by PMySQLQ** [comment]
Invulnerable for 5 seconds but can`t move.

You said it yourself

**Review by Suprcode — CHANGES_REQUESTED** [review]
some small changes to make before it can be accepted. also please update your branch to the current master - it's also bringing through healing circle again.

**Comment by MousaEqilan** [comment]
as i see some opinions in LOMCN regarding the skill , they want as it is on the official game 
I'm going to close  this up until I try and make it like the official game

**Pull request closed without merging**
