### PR TITLE
Fix skill bar display error

### PR DESCRIPTION
**Pull request by OuYangPlane**
Fix skill bar display error

### CODE REVIEW

**Comment by Sanjian** [comment]
can we not ban this moron? constantly pulling for selfish reasons regardless how many times its closed?

**Comment by PMySQLQ** [comment]
你要写的新的东西啊！比如 绝技系统 战场系统 副本系统 双攻城系统

**Comment by PMySQLQ** [comment]
细节的 你还有好多地方要修改

**Comment by PMySQLQ** [comment]
image

**Comment by PMySQLQ** [comment]
这样遮挡还有很多地方

**Comment by lodos3** [comment]
Haha , good luck with that one. Also need to put UI on a separate layers to
stop transparency tearing through.

**Pull request closed without merging**
